### ISSUE TITLE
Crashing on server3

### ISSUE THREAD

**Issue by clonm** [kngnm/alerting#1]
On server3, inside the influxdb container when I run `service influxdb status` I am getting `influxdb process is not running [ FAILED ]`

Persists across container recreation and `service influxdb restart`.

I'm starting it with this script:

```
#!/bin/bash -e

NAME=influxdb
HOSTNAME=influxdb
IMAGE=influxdb

INFLUXDB_DB=grafana
INFLUXDB_USER=<redacted>
INFLUXDB_PASS=<redacted>

REAL_IP=64.62.133.45
HOST_PORT1=8086
HOST_PORT2=8083
CONTAINER_PORT1=8086
CONTAINER_PORT2=8083

docker stop $NAME || true
docker rm $NAME || true

docker run --name $NAME --hostname "$HOSTNAME" -d \
    --env INFLUXDB_DB=$INFLUXDB_DB \
    --env INFLUXDB_USER=$INFLUXDB_USER \
    --env INFLUXDB_PASS=$INFLUXDB_PASS \
    -p $REAL_IP:$HOST_PORT1:$CONTAINER_PORT1 \
    -p $REAL_IP:$HOST_PORT2:$CONTAINER_PORT2 \
    $IMAGE
```

Any ideas?

**Comment by kngnm** [comment]
I am able to reproduce the error message.  I am starting the container with this slightly modified version of your script):
```
#!/bin/bash -e

NAME=influxdb
HOSTNAME=influxdb
IMAGE=alerting_influxdb

INFLUXDB_DB=grafana
INFLUXDB_USER=grafana
INFLUXDB_PASS=grafana

REAL_IP=10.20.96.170
HOST_PORT1=8086
HOST_PORT2=8083
CONTAINER_PORT1=8086
CONTAINER_PORT2=8083

docker stop $NAME || true
docker rm $NAME || true

docker run --name $NAME --hostname "$HOSTNAME" \
    --env INFLUXDB_DB=$INFLUXDB_DB \
    --env INFLUXDB_USER=$INFLUXDB_USER \
    --env INFLUXDB_PASS=$INFLUXDB_PASS \
    -p $REAL_IP:$HOST_PORT1:$CONTAINER_PORT1 \
    -p $REAL_IP:$HOST_PORT2:$CONTAINER_PORT2 \
    $IMAGE
```
Running the command I get:
```
root@influxdb:/# service influxdb status
influxdb process is not running [ FAILED ]
```

But I can also log in to the server using the influx client:

```
root@influxdb:/# influx -host 127.0.0.1 -port 8086 
Connected to http://127.0.0.1:8086 version 1.7.7
InfluxDB shell version: 1.7.7
> quit
root@influxdb:/#
```

I also tried running the command in the influxdb server in Kingman (which appears to be working fine), and get the same error.  I think that the `influxdb` base container does not use `service` (i.e. upstart) to start `influxdb`.   It's probably safe to disregard this error message.

**Comment by kngnm** [comment]
I pushed a bash script that launches the relevant parts of the project without `docker-compose`.  It works on my laptop, and with any luck it might work on `server3`, but I'm not getting my hopes up.  I'm probably several versions of `docker` ahead of `server3`
